version: "3"
services:
  nexus3:
    restart: always
    image: sonatype/nexus3
    container_name: nexus3
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "9091:8081"
    volumes:
      - ./nexus-data:/nexus-data:rw